// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

const defineConfig = (config: any) => config;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "yarn tsx prisma/seed.ts",
  },
  datasource: {
    // O CLI faz DDL (migrate, db push, introspect): precisa do dono do banco.
    // O role de runtime (`sf_app`) não tem esses privilégios — de propósito.
    url: process.env["DATABASE_URL_OWNER"],
  },
});
